### ISSUE TITLE
Replace antlr StringTemplate

### ISSUE THREAD

**Issue by nickmcdowall** [nickmcdowall/yatspec#13]
Yatspec currently uses version 3 of StringTemplate and upgrade to 4 is not a simple task. It is probably more worthwhile to use a simpler alternative e.g. JTwig for now which requires a smaller learning curve.

**Comment by hanfak** [comment]
Regarding commit [9d889ca20101c3fc016bd02667e3b5b2e9a20aa7](https://github.com/nickmcdowall/yatspec/commit/9d889ca20101c3fc016bd02667e3b5b2e9a20aa7)

Thanks for sorting this out. I had noticed this issue (in version 2020.3.9) when creating custom renderers (withCustomRenderers method) using the parent class (interface/abstract class) set as the type for the first argument. This did not pick up the renderer, as was doing a check on the type and not the parent type (instance of) and defaulted to using toString implementation (which is the object reference for HttpResponse in java.net.http package - which I was trying to custom render for html output). 

I actually did do a solution for this and was going to send a pull request after Christmas, but you got there before me. :-)

All the best,

Han
