### ISSUE TITLE
Fix Notes rendering

### ISSUE THREAD

**Issue by nickmcdowall** [nickmcdowall/yatspec#14]
Need to include notes in html output tests - manually spotted that Notes aren't rendered properly and need a fix.

**Comment by hanfak** [comment]
Regarding version: 2020.3.10

Are you getting the issue seen in the image, where the quotes are not rendered as " but as` &quot;`? 

The quotes are displayed as normal in version: release-2020.3.2

If so and you are fixing it, I will not do a fix and will wait for the latest version.

The example test can be seen here: [Example test](https://github.com/hanfak/new-yatspec-demo/blob/yatspec-quotes/src/test/java/_01reqandresponly/tests/UsecaseOneMoreExamplesTest.java)

Regards, 

Han

<img width="1145" alt="Screenshot 2020-12-29 at 13 04 28" src="https://user-images.githubusercontent.com/15229697/103285597-7f26a480-49d6-11eb-8523-fce9ae55e598.png">

**Comment by nickmcdowall** [comment]
Hi Han 👋 

Yes I spotted an issue and started working on a fix before Xmas but parked it when got the pesky covid 😷.

I'm all good now though and hope to take pick it up again soon 🙂.

**Comment by hanfak** [comment]
Damn, I hope you were not too badly affected. Good that you are back.

I am also looking at adding a dictionary, where yatpsec will highlight key words and hovering over the word will display the meaning. 

Is this something that you will be adding?

If not I will create an issue and add the feature

**Comment by nickmcdowall** [comment]
Thanks - yep we are all feeling much better.

Feel free to look into adding a dictionary - I have a vague memory of seeing code related to dictionary but that might have been removed. Might be some useful content if you look at the commit history.

For the above issue you mentioned it should be fixed on the latest release now. Shout if you spot anything though.

**Comment by hanfak** [comment]
Brilliant I will give it a go later this week

Yeah there was a "withCustom" script method that we used to add a java script files. Will give it a go, will be useful for our current work project

Could to hear your family is doing well
