### ISSUE TITLE
Allow a Renderer to generate raw html

### ISSUE THREAD

**Issue by alfanse** [nickmcdowall/yatspec#23]
As an dev, 
I want to show the content of a database table on the yatspec output.
So that readers can see the before and after changes to the DB

I used to implement the interface [Renderer](https://github.com/nickmcdowall/yatspec/blob/master/src/main/java/com/googlecode/yatspec/rendering/Renderer.java) with a [ResultSetRenderer](https://github.com/alfanse/embers/blob/nicks-yatspec/embers-acceptance-tests/src/main/java/yatspec/renderers/ResultSetRenderer.java) that returns html for direct addition to the page.

Problem is the output of the Render filter is passed to the [PebbleEngine](
https://github.com/nickmcdowall/yatspec/blob/master/src/main/java/com/googlecode/yatspec/rendering/html/HtmlResultRenderer.java#L51) which notices its not a SafeString, so it escapes the string its passed, ignoring all my html layout 😢 
see pebble [FilterExpression](https://github.com/PebbleTemplates/pebble/blob/master/pebble/src/main/java/com/mitchellbosecke/pebble/node/expression/FilterExpression.java#L68)

How can I get yatspec to tell pebble, this is a safe string?

**Comment by alfanse** [comment]
Possible PR to fix this issue in the "captured interactions" section of the yatspec.peb https://github.com/nickmcdowall/yatspec/pull/24

**Comment by nickmcdowall** [comment]
Hey Alex! Sorry for the delay in getting back to you. 

Your PR seems to do the trick and I couldn't see any issues when I had a little play so let's go for it 👍 . Thanks for looking into solving the issue yourself 🥇
