### ISSUE TITLE
Allow generating sequence diagrams for Cucumber tests

### ISSUE THREAD

**Issue by lukasz-gryzbon** [nickmcdowall/yatspec#4]
If a project has a substantially large Cucumber test base and would like to introduce Yatspec, it may not be feasible or economical to convert all the existing tests.

What would be very useful though is to be able to generate the sequence diagrams from the existing Cucumber tests.

Since the existing Cucumber reports already include the specs, as a compromise the sequence diagrams don't necessarilly need to include them.

So the idea is to keep the gherkin specs and the steps implementations as they in Cucumber and only have an add-on that would generate the sequence diagrams in addition to what is already there (the Cucumber reports).

**Comment by nickmcdowall** [comment]
Good idea. A prototype solution is available that will need some refinement but may be useful in the meantime.
