### ISSUE TITLE
Add a hook for a plugin

### ISSUE THREAD

**Issue by lukasz-gryzbon** [nickmcdowall/yatspec#5]
It would be very helpful if it was possible to register plugin(s) with Yatspec which would allow to override where the data for the LSD comes from. It could still come from TestState. However, the plugin could also source the data from somewhere else.

This is a vital functionality for enabling LSDs in E2E tests,

When experimented, adding additional processing inside the @AfterEach method didn't work.

**Comment by nickmcdowall** [comment]
Hey thanks for the feedback - as discussed let's see if using an annotated **method** which will get invoked after each test but before the sequence diagram will be sufficient.

See `com.googlecode.yatspec.junit.@PostTestProcessing` which has just been added and can be used in tests that use the junit5 `SequenceDiagramExtension`.

Add it to a method in the test class (or hierarchy)

**Comment by lukasz-gryzbon** [comment]
Thanks! That's great!
